pipeline:
  identifier: Build_gregkroon_go_pipeline_sample_1715635192289
  name: Build go-pipeline-sample
  orgIdentifier: default
  projectIdentifier: gosample
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: gregkroon/go-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotestcoverage
                  name: go_test_coverage
                  spec:
                    shell: Sh
                    command: |-
                      ls -la

                      ##go test -coverprofile=coverage.out ./...
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotestreport
                  name: go_test_report
                  spec:
                    shell: Sh
                    command: "#export GOBIN=/home/harness/go/bin\n#\t\texport PATH=/home/harness/go/bin:$PATH\n#\t\techo $PATH\n#\t\tgo install github.com/jstemmer/go-junit-report/v2@latest\n#\t\tgo test -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml"
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - /harness/report.xml
                  timeout: ""
                  type: Run
              - step:
                  type: SscaOrchestration
                  name: SBOM Orchestration
                  identifier: SBOM_Orchestration
                  spec:
                    mode: generation
                    tool:
                      type: Syft
                      spec:
                        format: spdx-json
                    source:
                      type: docker
                      spec:
                        connector: docker
                        image: munkys123/gosample
                    sbom_drift:
                      base: last_generated_sbom
                    resources:
                      limits:
                        memory: 500Mi
                        cpu: "0.5"
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: docker
                    repo: munkys123/gosample
                    tags:
                      - latest
                    caching: true
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          slsa_provenance:
            enabled: true
            attestation:
              type: cosign
              spec:
                private_key: cosignkey
                password: cosignpass
        type: CI
        description: ""
